version: '3.7'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana_container
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitore_network
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb:1.8.4
    container_name: influxdb_container
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitore_network
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
networks:
  monitore_network:
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
    